---
title: "Impacts and Echoes: The Lasting Influence of the White House Conference on Food, Nutrition and Health"
---

The 1969 White House Conference on Food, Nutrition and Health was incredibly influential on the direction of food and nutrition policy in the United States. The conference produced recommendations leading to federal legislation and programs to alleviate hunger and malnutrition, improve consumer’s nutrition knowledge through education and labeling, and monitor the nutritional status of the population. Fifty years later, the conference’s legacy was revisited at a conference convened by Harvard University and Tufts University. Our project reviews the literature contributing to the first author’s keynote speech at the conference, its influencers, and influences. We focus on the highlights of five domains that set the stage for the conference: social, food, nutrition science, public health data, and policy events. In the paper, we briefly describe the conference, its proposed directions, and its lasting legacy in these five domains. More specifically, on this website, we have developed interactive timelines to visualize the major events of the past 50 years, analyze the 1969 White House Conference Report with the use of computational text analysis and text networks, and conduct some preliminary text analysis of the nutrition literature before and after 1990. 